var fall = [];
var flap = [];
var type = [];
var fall1;
var flap1;
var type1;
var value = 0;
var splinter = [];
var doodads = [];
var cloud = [];
var bird;
//var splat; 
var splat = [];
  var gr;
var phonepic = [];
var sound_music,sound_press,sound_lose;
  
function preload()
{
  sound_music = loadSound("milky-chu_-_03_-_Simpsons_Mas_Game.mp3");
  sound_press = loadSound("click.wav");
  sound_lose = loadSound("lose.wav");
  fall1 = loadAnimation("fall_01.png","fall_12.png");
  flap1 = loadAnimation("flappy_01.png","flappy_08.png");
  type1 = loadAnimation("type_01.png","type_08.png");
  bird = loadAnimation("bird_01.png","bird_08.png");
  //splat = loadAnimation("death_01.png","death_11.png");
  // fall[0] = loadImage("fall_01.png");
  // fall[1] = loadImage("fall_02.png");
  // fall[2] = loadImage("fall_03.png");
  // fall[3] = loadImage("fall_04.png");
  // fall[4] = loadImage("fall_05.png");
  // fall[5] = loadImage("fall_06.png");
  // fall[6] = loadImage("fall_07.png");
  // fall[7] = loadImage("fall_08.png");
  // fall[8] = loadImage("fall_09.png");
  // fall[9] = loadImage("fall_10.png");
  // fall[10] = loadImage("fall_11.png");
  // fall[11] = loadImage("fall_12.png");
  // flap[0] = loadImage("flappy_01.png");
  // flap[1] = loadImage("flappy_02.png");
  // flap[2] = loadImage("flappy_03.png");
  // flap[3] = loadImage("flappy_04.png");
  // flap[4] = loadImage("flappy_05.png");
  // flap[5] = loadImage("flappy_06.png");
  // flap[6] = loadImage("flappy_07.png");
  // flap[7] = loadImage("flappy_08.png");
  // type[0] = loadImage("type_01.png");
  // type[1] = loadImage("type_02.png");
  // type[2] = loadImage("type_03.png");
  // type[3] = loadImage("type_04.png");
  // type[4] = loadImage("type_05.png");
  // type[5] = loadImage("type_06.png");
  // type[6] = loadImage("type_07.png");
  // type[7] = loadImage("type_08.png");
  splinter[0] = loadImage("splinter_01.png");
  splinter[1] = loadImage("splinter_02.png");
  splinter[2] = loadImage("splinter_03.png");
  splinter[3] = loadImage("splinter_04.png");
  splinter[4] = loadImage("splinter_05.png");
  splinter[5] = loadImage("splinter_06.png");
  splinter[6] = loadImage("splinter_07.png");
  doodads[0] = loadImage("doodad_01.png");
  doodads[1] = loadImage("doodad_02.png");
  doodads[2] = loadImage("doodad_03.png");
  cloud[0] = loadImage("clouds_01.png");
  cloud[1] = loadImage("clouds_02.png");
  cloud[2] = loadImage("clouds_03.png");
  cloud[3] = loadImage("clouds_04.png");
  splat[0] = loadImage("death_01.png");
  splat[1] = splat[0];
  splat[2] = loadImage("death_02.png");
  splat[3] = splat[2];
  splat[4] = loadImage("death_03.png");
  splat[5] = splat[4];
  splat[6] = loadImage("death_04.png");
  splat[7] = splat[6];
  splat[8] = loadImage("death_05.png");
  splat[9] = splat[8];
  splat[10] = loadImage("death_06.png");
  splat[11] = splat[10];
  splat[12] = loadImage("death_07.png");
  splat[13] = splat[12];
  splat[14] = loadImage("death_08.png");
  splat[15] = splat[14];
  splat[16] = loadImage("death_09.png");
  splat[17] = splat[16];
  splat[18] = loadImage("death_10.png");
  splat[19] = splat[18];
  splat[20] = loadImage("death_11.png");
  splat[21] = splat[20];
  gr = loadImage("ground.png");
  phonepic[0] = loadImage("phone_00.png");
  phonepic[1] = loadImage("phone_01.png");
  phonepic[2] = loadImage("phone_02.png");
  phonepic[3] = loadImage("phone_03.png");
  phonepic[4] = loadImage("phone_04.png");
  phonepic[5] = loadImage("phone_05.png");
  phonepic[6] = loadImage("phone_06.png");
  phonepic[7] = loadImage("phone_07.png");
  phonepic[8] = loadImage("phone_08.png");
  phonepic[9] = loadImage("phone_09.png");
  phonepic[10] = loadImage("phone_10.png");
  phonepic[11] = loadImage("phone_11.png");
  phonepic[12] = loadImage("phone_12.png");
  phonepic[13] = loadImage("phone_13.png");
  phonepic[14] = loadImage("phone_14.png");
  phonepic[15] = loadImage("phone_15.png");
  phonepic[16] = loadImage("phone_16.png");
  phonepic[17] = loadImage("phone_17.png");
  phonepic[18] = loadImage("phone_18.png");
  phonepic[19] = loadImage("phone_19.png");
  phonepic[20] = loadImage("phone_20.png");
  
}